version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: hibernate_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world
      MYSQL_USER: hibernate_user
      MYSQL_PASSWORD: hibernate_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:7.0
    container_name: hibernate_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    command: redis-server --appendonly yes

volumes:
  mysql_data:
  redis_data:

networks:
  app_network:
    driver: bridge
